### ISSUE TITLE
Update to work with latest version of tesseract 3.04

### ISSUE THREAD

**Issue by charlesw** [charlesw/tesseract-vs2012#6]
The latest version of tesseract 3.04 (currently unreleased) has made some changes to the source structure, i.e. added and removed some files, which are not reflected in the patch. Fix it!

**Comment by nguyenq** [comment]
Any update on this issue? Thanks.

**Comment by charlesw** [comment]
I think I've already fixed this in d3cfc60294b6ca, just forgot to close the issue. Can you confirm that the latest release works for you?

**Comment by nguyenq** [comment]
Wow, I've long suspected that patch was it, but since the issue was left open, which caused me to have some doubt. I did not realize that tesseract-ocr's master branch has become 3.05 Dev. I switched to 3.04 and -- bingo! -- got all the Tesseract 3.04 binaries generated.

Thank you very much, Charles.

Best regards,
Quan

**Comment by charlesw** [comment]
No problem
